apiVersion: v1
kind: Secret
metadata:
  name: future-me-secrets
  namespace: future-me
type: Opaque
stringData:
  groq-api-key: "gsk_xxxxxxxx" # Groq API Key
  github-token: "ghp_xxxxxxxx"    # PAT for GitHub account
