apiVersion: v1
kind: Secret
metadata:
  name: future-me-secrets
  namespace: future-me
type: Opaque
stringData:
  openai-api-key: "xxxxxxxx"   # OpenAI key
  github-token: "xxxxxxxx"    # PAT for GitHub account
